### ISSUE TITLE
datasets can not be downloaded 

### ISSUE THREAD

**Issue by muzixilin** [FingerRec/Faster-rcnn_Ship_detection#1]
hello, dear Mr.author.[airbus-ship-detection-data](https://www.kaggle.com/c/airbus-ship-detection/data),this dataset cant be downloaded in the websites although i have completed the registration.It tells that the dataset is for Kaggle contest and i have no access to obtain the data.I cant not to run the projects on the MATLAB 2018b.so i want to ask for your help.Give me some advice.Looking forward to your reply.Thanks.

**Comment by FingerRec** [comment]
Join Competition?
